/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workoutjournal;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
    Workout newDay;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        newDay = new Workout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        removeSetButton = new javax.swing.JButton();
        exName = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        reps = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        toSArea = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        theDate = new org.jdesktop.swingx.JXDatePicker();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        saveCurWorkout = new javax.swing.JButton();
        loadPrevWorkout = new javax.swing.JButton();
        overWriteExisting = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSetButton.setText("Add Set");
        addSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addSetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel1.setText("Exercise Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel2.setText("Weight:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel3.setText("Repetitions:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        removeSetButton.setText("Remove Set");
        removeSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeSetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));
        getContentPane().add(exName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 100, -1));
        getContentPane().add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 100, -1));
        getContentPane().add(reps, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 100, -1));

        jScrollPane1.setViewportView(toSArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 330));

        jLabel4.setText("Workout");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel5.setText("Add set");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel6.setText("Load old workout");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        theDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theDateActionPerformed(evt);
            }
        });
        theDate.setDate(new Date());
        getContentPane().add(theDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 150, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        saveCurWorkout.setText("Save Workout");
        saveCurWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCurWorkoutActionPerformed(evt);
            }
        });
        getContentPane().add(saveCurWorkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 160, 50));

        loadPrevWorkout.setText("Load");
        loadPrevWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPrevWorkoutActionPerformed(evt);
            }
        });
        getContentPane().add(loadPrevWorkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        overWriteExisting.setText("Overwrite if exists");
        overWriteExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overWriteExistingActionPerformed(evt);
            }
        });
        getContentPane().add(overWriteExisting, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSetButtonActionPerformed
        // TODO add your handling code here:
        
        
        boolean isReady;
        
        if(exName.getText().equals("")){
            isReady=false;       
            System.out.println("Please make sure all fields are filled out");
        }else if(weight.getText().equals("")){
            isReady=false;
            System.out.println("Please make sure all fields are filled out");
        }else if(reps.getText().equals("")){
            isReady=false;
            System.out.println("Please make sure all fields are filled out");
        }else
            isReady = true;
        if(isReady){  
        String ex = exName.getText();
        int wt = Integer.parseInt(weight.getText());
        int rps = Integer.parseInt(reps.getText());
        Motion a = new Motion(ex,wt,rps);
        newDay.addSet(a);
        exName.setText("");
        weight.setText("");
        reps.setText("");
        toSArea.setText(newDay.toString());
        System.out.println("Set added");
        }
        
    }//GEN-LAST:event_addSetButtonActionPerformed

    private void theDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_theDateActionPerformed

    private void saveCurWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCurWorkoutActionPerformed
        // TODO add your handling code here:
        
        Date today = Calendar.getInstance().getTime();
        
        String tDay = new SimpleDateFormat("MM_dd_yyyy").format(today);
        File test = new File("saves/"+tDay);
        boolean ow = overWriteExisting.isSelected();
        if((!test.exists()|| ow)&&newDay.numSets>0){
            System.out.println("Workout saved"+ tDay);
        
        // Write to disk with FileOutputStream
        FileOutputStream f_out = null;
        try {
            f_out = new FileOutputStream("saves/"+tDay);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Write object with ObjectOutputStream
        ObjectOutputStream obj_out = null;
        try {
            obj_out = new ObjectOutputStream (f_out);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            // Write object out to disk
            obj_out.writeObject ( newDay );
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            System.out.println("Save action not performed");
        }
    }//GEN-LAST:event_saveCurWorkoutActionPerformed

    private void loadPrevWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPrevWorkoutActionPerformed
        // TODO add your handling code here:
        
        Date tmp = theDate.getDate();
        String tDay = new SimpleDateFormat("MM_dd_yyyy").format(tmp);
        File file = new File("saves/"+tDay);
        // Read from disk using FileInputStream
        if(file.exists()){
        FileInputStream f_in = null;
        try {
            f_in = new FileInputStream("saves/"+tDay);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Read object using ObjectInputStream
        ObjectInputStream obj_in = null;
        try {
            obj_in = new ObjectInputStream (f_in);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Read an object
        Object obj = null;
        try {
            obj = obj_in.readObject();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

            if (obj instanceof Workout)
            {
                    // Cast object to a Vector
                    Workout load = (Workout) obj;
                    newDay = load;
                    // Do something with vector....
                    toSArea.setText(newDay.toString());
                    System.out.println(newDay.toString());
            }
        }
        else{
            toSArea.setText("The date you have selected currently has no workout saved!");
        }
    }//GEN-LAST:event_loadPrevWorkoutActionPerformed

    private void removeSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSetButtonActionPerformed
        // TODO add your handling code here:
        String name = exName.getText();
        int numReps = Integer.parseInt(reps.getText());
        int wgt = Integer.parseInt(weight.getText());
        newDay.removeSet(name,wgt,numReps);
        toSArea.setText(newDay.toString());
    }//GEN-LAST:event_removeSetButtonActionPerformed

    private void overWriteExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overWriteExistingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overWriteExistingActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSetButton;
    private javax.swing.JTextField exName;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadPrevWorkout;
    private javax.swing.JCheckBox overWriteExisting;
    private javax.swing.JButton removeSetButton;
    private javax.swing.JTextField reps;
    private javax.swing.JButton saveCurWorkout;
    private org.jdesktop.swingx.JXDatePicker theDate;
    private javax.swing.JTextPane toSArea;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
